name: Build
# 定义触发条件
# 当代码库发生推送操作时触发这个工作流程
on:
  push:
    branches: [ "**" ]

# 包含一个或多个作业的部分
# 可以根据需要自定义它们的名称，以便更好地描述作业的目的
jobs:
  # 作业 1
  build-bookmarker-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest # 指定作业运行环境
    # 默认设置
    defaults:
      run:
        working-directory: ./bookmarker-api
    # 包含一系列步骤
    steps:
      # name 用于为步骤指定一个描述性的名称
      # uses 用于引用外部操作或动作
      # run：这是一个用于执行命令或脚本的步骤。在这个例子中，run 步骤中的命令将在作业的运行环境中执行
      # ${{ }}：这是 YAML 中的变量语法。在这个例子中，${{ github.ref }} 引用了 GitHub 仓库的引用（即分支）
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify

      # 检查当前分支是否为 main 分支
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          ./mvnw clean package jib:dockerBuild -DskipTests
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api

#  # 作业 2
#  build-bookmarker-ui:
#    name: Build bookmarker-ui
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./bookmarker-ui-nextjs
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Setup Node.js 16
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16
#          cache: 'yarn'
#          cache-dependency-path: bookmarker-ui-nextjs/yarn.lock
#      - name: Install dependencies
#        run: yarn
#
#      - name: Build
#        run: yarn build
#
#      - if: ${{ github.ref == 'refs/heads/main' }}
#        name: Build and Publish Docker Image
#        run: |
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/bookmarker-ui-nextjs .
#          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-ui-nextjs
